### ISSUE TITLE
cascading configuration

### ISSUE THREAD

**Issue by mottosso** [mottosso/be#29]
### Goal

To enable per-item configuration, such as additional environment variables and aliases.

```bash
$ be in hulk bruce rigging --enter
$ maya
Launching Maya 2015..
```

```bash
$ be in hulk bruce rigging --enter
$ maya
Customised, launching Maya 2016..
```

### Implementation

The `be.yaml` configuration file is looked up at each level of the development directory.

E.g.

```
▸ hulk
  ▸ be.yaml
  ▾ assets
    ▾ bruce
      ▾ be.yaml
```

Each key is appended to the upper, children overwrite parents.

**hulk/be.yaml**

```yaml
alias:
- maya: start "" "maya2015.exe"
```

**bruce/be.yaml**

```yaml
alias:
- maya: start "" "maya2016.exe"
```

**Comment by hommes-doutant** [comment]
Sometimes environment variable need to be declared only for specific software. Like `MAYA_SCRIPT_PATH` or `MAYA_PLUG_IN_PATH`. I don't see how this would be done with only an alias system.

I think it would fit well to declare software in the **be.yaml** :
``` yaml
software:
  Maya:
    command: start "" "maya2016.exe"
     env:
        MAYA_PLUG_IN_PATH: path/to/plugins
        MAYA_SCRIPT_PATH: path/to/scripts
```

What do you think of this design ?
