### ISSUE TITLE
be update

### ISSUE THREAD

**Issue by mottosso** [mottosso/be#37]
### goal

To synchronise a running project with it's source configuration.
Suggested by @hommes-doutant [here](https://github.com/mottosso/be/issues/3).

### implementation

Updating an existing project could look like this.

```bash
$ be update spiderman
```

Following which `be.yaml`, `templates.yaml` and `inventory.yaml` is updated.

The name of the given project must be given, similar to how it would normally be given during `be in` or `be ls` etc.

Only projects started from a preset would support being updated. When starting a project via `be new`, a reference to it's source is embedded in `be.yaml`.

**be.yaml**

```yaml
source: mottosso/be-film
```

If the source is local, then it's local name is provided.

```yaml
source: mylocalpreset
```

The source is then used to determine from where to pull updates.

### overlap

In the case of updating a configuration file with modified values, what should happen?

**original**

```yaml
environment:
  MYVAR: My value
```

**old**

```yaml
environment:
  MYVAR: My value
  MYADDEDVAR: Another value
```

**new**

```yaml
environment:
  MYVAR: New value
```

**result**

```yaml
environment:
  MYVAR: New value
  MYADDEDVAR: Another value
```

A simple `{}.update({})` would suffice here, but what about when modifications involve removal of data?

**original**

```yaml
environment:
  MYVAR: My value
  MYOTHERVAR: Another value
```

**new**

```yaml
environment:
  MYVAR: My value
```

Or modifications to an original value?

**original**

```yaml
environment:
  MYVAR: My short value
```

**new**

```yaml
environment:
  MYVAR: My longer value
```

### problem

A number of questions arise that might make the experience not-so-intuitive and unsafe.
