### ISSUE TITLE
environment.yaml

### ISSUE THREAD

**Issue by mottosso** [mottosso/be#5]
### Goal

Provide project designers with the ability to add additional environment variables on a per-project basis

### Implementation

```yaml
MY_VARIABLE: c:\my\value
```

Variables are also expanded.

```yaml
MY_OTHERVARIABLE: {cwd}/special/{root}/dir
```

**Comment by mottosso** [comment]
Implemented as a key of `be.yaml`.

```yaml
environment:
    MYVARIABLE: somevalue
    PATH: ["$PATH", "$BE_CWD/myvalue"]
    MEGA: "$BE_USER is User"
```

Supports:

- Plain key/value data
- Resolving an existing environment variable, using `$VAR` syntax
- Resolving variables from entered environment, such as `BE_USER`
